### PR TITLE
Adding scripted build & installation

### PR DESCRIPTION
**Pull request by evgeniibuchnev**
Compiled all already mentioned in Readme into one script for an easy installation with one liner also added into Readme.

### CODE REVIEW

**Comment by amigniter** [comment]
Hi,
Thanks for your good intention to contribute. It is a nice thing to add but I'd like you to consider improving it a bit.
`export PKG_CONFIG_PATH=/usr/local/freeswitch/lib/pkgconfig`
We do not need to export the path if it's not actually used. You can use bash scripting to check if it exists and then export it.

**Comment by evgeniibuchnev** [comment]
Hi there,
Thanks for the suggestion, just added logic to check if path exists before exporting.

**Comment by amigniter** [comment]
Right, exactly. But if user installed FS at a custom location other than this one then we can't know it and it will require setting it manually.

**Comment by evgeniibuchnev** [comment]
Yep, this is just an easy way to build and deploy if you have everything default. Personally will be using it as automated build and deploy. Thanks for merging and love mod_audio_stream!

**Pull request merged**
